# -*- coding: utf-8 -*-
"""AutokerasResultsAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-JzRJuf-4eRkqE5zbhpk9RapYP80mSSd
"""

import pandas as pd
model_dir='/mnt/Models'
results_dir = "/mnt/Results"



for iter_pers_label in ['o','c','e','a','n']:
    for iter_gender in ['male','female']:
        for iter_feature in ['talkturn','sentiment','time','speechtrait']:
            print(f"Personality Label: {iter_pers_label}, Gender: {iter_gender}, Feature: {iter_feature}")
            logfilename = results_dir+f"/fit_results_{iter_feature}_{iter_pers_label}_{iter_gender}.csv"
            #model_checkpoint = ModelCheckpoint('./Models/TalkTurn_'+str(iter_gender)+'_'+str(iter_pers_label)+'.tf', verbose=1, save_best_only=True,save_format='tf')
            model_filename = f"./Models/{iter_feature}_{iter_gender}_{iter_pers_label}"
            exec(f"df_fit_results_{iter_feature}_{iter_pers_label}_{iter_gender} = pd.read_csv(logfilename,sep=';')")
            exec(f"print(df_fit_results_{iter_feature}_{iter_pers_label}_{iter_gender}.min())")

df_fit_results_sentiment_a_female.min()

df_fit_results_sentiment_a_female

df_fit_results_sentiment_a_female.std()

[df_fit_results_sentiment_a_female[1:5].std(),df_fit_results_sentiment_a_female[].std()]

df_talkturn_test_male_meta=pd.read_csv('./Results/test_male_meta.csv')
df_talkturn_test_female_meta=pd.read_csv('./Results/test_female_meta.csv')

import pandas as pd
model_dir='/mnt/Models'
results_dir = "/mnt/Results"



for iter_gender in ['male','female']:
    for iter_feature in ['talkturn','sentiment','time','speechtrait','alltextual']:
        print(f"Gender: {iter_gender}, Feature: {iter_feature}")
        resfilename = results_dir+f"/{iter_feature}_{iter_gender}_test.csv"
        exec(f"df_results_{iter_feature}_{iter_gender} = pd.read_csv(resfilename,sep=',')")

alltextual_female = pd.concat([df_talkturn_test_female_meta.reset_index(drop=True),df_results_alltextual_female.reset_index(drop=True)], axis=1)

alltextual_male = pd.concat([df_talkturn_test_male_meta.reset_index(drop=True),df_results_alltextual_male.reset_index(drop=True)], axis=1)

alltextual_male.drop(["Unnamed: 0"],axis = 1,inplace=True)

alltextual_female.drop(["Unnamed: 0"],axis = 1,inplace=True)

alltextual = alltextual_male.append(alltextual_female)

alltextual.to_csv("/mnt/Results/alltextual_results.csv")

alltextual

